name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          ./run.bash
        working-directory: test
      - name: Build
        run: |
          docker build --file docker/Dockerfile --output out --target output .
      - name: Checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            out/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            checksum.txt
            out/*
